# fly.toml app configuration file generated for lively-resonance-8575 on 2023-06-22T23:00:32+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-resonance-8575"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
